### ISSUE TITLE
After unregistering pytest plugin continues to print messages

### ISSUE THREAD

**Issue by capgelka** [JetBrains/teamcity-messages#101]
I had a problem with encoding on teamcity agent.

encoding set's auromcatically to cp1252 so I got

>  [16:02:09][Step 4/6] INTERNALERROR>   File "c:\python35\lib\site-packages\teamcity\messages.py", line 104, in testStarted
> [16:02:09][Step 4/6] INTERNALERROR>     self.message('testStarted', name=testName, captureStandardOutput=captureStandardOutput, flowId=flowId)
> [16:02:09][Step 4/6] INTERNALERROR>   File "c:\python35\lib\site-packages\teamcity\messages.py", line 57, in message
> [16:02:09][Step 4/6] INTERNALERROR>     message = message.encode(self.encoding)
> [16:02:09][Step 4/6] INTERNALERROR>   File "c:\python35\lib\encodings\cp1252.py", line 12, in encode
> [16:02:09][Step 4/6] INTERNALERROR>     return codecs.charmap_encode(input,errors,encoding_table)
> [16:02:09][Step 4/6] INTERNALERROR> UnicodeEncodeError: 'charmap' codec can't encode characters in position 139-145: character maps to <undefined>

This looks's like a windows problem, not python or teamcity-messages.

To solve this I tried to unregister plugin and register again with
```
    def fixed_configure(config):
        if config.option.no_teamcity >= 1:
            enabled = False
        elif config.option.teamcity >= 1:
            enabled = True
        else:
            enabled = is_running_under_teamcity()
        if enabled:
            output_capture_enabled = getattr(config.option, 'capture', 'fd') != 'no'
            coverage_controller = _get_coverage_controller(config)

            config._teamcityReporting = EchoTeamCityMessages(output_capture_enabled, 
                                                             coverage_controller)
            config._teamcityReporting.teamcity.encoding = 'utf8'
            config.pluginmanager.register(config._teamcityReporting)
```
function

But unconfiguring didn't work as I expected. Info about plugin deletes from pluginmanager attributes but messages for teamcity stiil printing to stdout. (So if I both unregister and register patched version it's prints all messages twice - with old and new encoding).

Code to unregister module:

```
plugin = config.pluginmanager.getplugin("pytest-teamcity")
plugin.pytest_unconfigure(config)
```
Or more manually
```
plugin = config.pluginmanager.getplugin("pytest-teamcity")
config.pluginmanager.unregister(plugin)
config.pluginmanager._plugin2hookcallers.pop(sys.modules['teamcity.pytest_plugin']) 
```
Both doesn't work as expected.

P.S. I create [pull request](https://github.com/JetBrains/teamcity-messages/pull/100) that solves original problem, but this behaviour with unregistering looks like a bug, so I decide to create this issue.

**Comment by shalupov** [comment]
Probably this counts as pytest issue? I don't see any not standard code in pytest plugin initialization

**Comment by capgelka** [comment]
Most likely you are right. I will I'll try to check it with last pytest version and with some other simple plugin.

**Comment by capgelka** [comment]
That's my mistake and not a bug: pluggy `load_setuptools_entrypoints` funtion was called before my code and make me think that pytest-teamcity has been already loaded.

But it only appeared in `pluginmaneger._name2plugin` without any hooks. So it was really registered after my call. So after adding `@pytest.hookimpl(trylast=True)` decorator to my local pytest_configure function encoding changes as I expected.
