### ISSUE TITLE
Flake8 switched to pycodestyle from pep8, breaking teamcity-messages import of pep8

### ISSUE THREAD

**Issue by cmaloney** [JetBrains/teamcity-messages#103]
teamcity-messages for flake8 pulls in pep8 directly:
https://github.com/JetBrains/teamcity-messages/blob/e56f83206a0f84da09fa682418b2c55d39828a9d/teamcity/flake8_plugin.py#L1

But flake8 2.6.0 (recently released) swiced to `pycodestyle` instead of `pep8` as the binary to run.

This makes it so that CI jobs fail since `pep8` can't be imported (And isn't dependend upon by teamcity-messages).

doing a try/catch around `import pycodestyle as pep8` or something similar will likely fix this.

Sample failed build (use guest login):
https://teamcity.mesosphere.io/viewLog.html?buildId=298303&buildTypeId=DcosIo_Dcos_CodeQuality&tab=buildLog#_focus=413

**Comment by shalupov** [comment]
Thanks! released 1.19
