### ISSUE TITLE
Allow to suppress test status reporting under flake8 in TeamCity

### ISSUE THREAD

**Issue by ogerovich** [JetBrains/teamcity-messages#108]
Hello,
I am running flake8 like this in TeamCity:
`python -m flake8 --config=tox.ini --exit-zero --output-file=flake8.txt C:\foo\bar`

TeamCity automatically converts each message from pep8 into a test. While that may be desirable in some cases, in our case it generates >20000 tests. I don't want them to flood TeamCity database or show up on the build overview. Instead, we have our own way to process the output file and present the results. I need teamcity-messages installed for other builds on the same machine. Current flake8 option --teamcity does not take a value, so I can't find a way to suppress that functionality.

Let me know if this issue really belongs in flake8.

**Comment by shalupov** [comment]
released 1.20 with --no-teamcity option for flake8 >= 3.x

**Comment by ogerovich** [comment]
Thank you, Leonid! I tested `--no-teamcity=false` with flake8 3.0.3 and teamcity-messages 1.20. It worked!

**Comment by shalupov** [comment]
np. Also I think just --no-teamcity is enough, --no-teamcity=false looks like negating negation.

**Comment by ogerovich** [comment]
Oh, that was a typo in my comment. I'm actually using --no-teamcity=true. If I do as you suggest, flake8 seems to ignore --output-file option that follows. My command that works now is `python -m flake8 --config=tox.ini --exit-zero --no-teamcity=true --output-file=flake8.txt C:\foo\bar`.
