### ISSUE TITLE
Does teamcity-messages support nosetests running from ssh sesison

### ISSUE THREAD

**Issue by bozhaojiangkcg** [JetBrains/teamcity-messages#110]
Hi, Leonid,

I have a scenario that nosetests is run on a server (not the teamcity agent runs from) with ssh session.  The tests results used be reported correctly (with teamcity-messages 1.7), but it stops working with newer version of 1.20. 

I make sure teamcity agent and nosetest server are both installed with teamcity-messages 1.20 and nosetests 1.37. Does teamcity-messages process nosetests std output for tests report or does it read from some files nosetests generate? 

Thanks,

Bozhao

**Comment by shalupov** [comment]
Almost nothing changed in that area from 1.7. Probably you've got a broken install, try a recipe from me for other user: https://github.com/JetBrains/teamcity-messages/issues/109#issuecomment-240364962

**Comment by bozhaojiangkcg** [comment]
I tried the recipe already. I suspect the issue is related to some environment settings? There is no teamcity agent running on the server running nosetests. Does teamcity-messages depends on any teamcity environment settings to print out in format that teamcity recognizable?

**Comment by shalupov** [comment]
It is, see https://github.com/JetBrains/teamcity-messages/blob/master/teamcity/__init__.py

You may try from the console set this variable and run tests, teamcity-messages should output service messages to console (see https://confluence.jetbrains.com/display/TCD10/Build+Script+Interaction+with+TeamCity)
