### ISSUE TITLE
Provide number of tests if possible

### ISSUE THREAD

**Issue by throwable-one** [JetBrains/teamcity-messages#116]
With out of number of tests Intellij can't draw progress bar correclty

**Comment by shalupov** [comment]
@throwable-one You should be ready that testCount will reflect exact number of tests only if everything ok with collect and setup/teardown stages. Else you may get additional tests or testCount message after already reported tests

**Comment by throwable-one** [comment]
@shalupov does not work for unittest.
testcount reported for nose and py but not for unit

**Comment by shalupov** [comment]
@throwable-one found a way to fix it too

**Comment by throwable-one** [comment]
Thank you!
