### ISSUE TITLE
Incorrect test class reported for derived classes (unittest)

### ISSUE THREAD

**Issue by throwable-one** [JetBrains/teamcity-messages#117]
File ``test_test.py``
```
class BaseTestCases:
    class TestAbstract(TestCase):
        def test_a(self):
            raise Exception()


class TestDerived(BaseTestCases.TestAbstract):
    def test_b(self):
        print("Running from derived class")
```

What is the name of ``test_a``?
UnitTest says ``: test_a (test_test.TestDerived)``

But your runner reports
``name='test_test.TestAbstract.test_a'``

That is not true. You can't run ``test_test.TestAbstract.test_a``, so please make your runner behave like unittest.

**Comment by shalupov** [comment]
You want it to be reported as test_test.TestDerived.test_a, right?

**Comment by throwable-one** [comment]
@shalupov yes, just like UnitTest does.

**Comment by shalupov** [comment]
Ok, after some investigation: if you won't run test_test.TestAbstract.test_a test explicitly it won't be reported as test_test.TestAbstract.test_a. So, as designed
