### ISSUE TITLE
Capture stdout and stderr for unittest

### ISSUE THREAD

**Issue by throwable-one** [JetBrains/teamcity-messages#118]
It is impossible to synchornize output now. Please capture stdout and stderr in unittest and provide them as you do it for pytest and nosetest

**Comment by shalupov** [comment]
@throwable-one  anyway, you need to run unittest with --buffer or specifying buffer=True for the runner

**Comment by throwable-one** [comment]
@shalupov thanks
by the way, can you please capture nose errors as well?

**Comment by throwable-one** [comment]
Following info is written to STDERR anyway
Ran 1 test in 0.259s

FAILED (failures=1)

**Comment by throwable-one** [comment]
Oops: https://youtrack.jetbrains.com/issue/PY-22505
We need to report output on flush, not on "test stop" using latest active test. Is it possible?

**Comment by shalupov** [comment]
As for this issue teamcity-messages now supports --buffer anyway
