### ISSUE TITLE
test name reported before "testStarted"

### ISSUE THREAD

**Issue by throwable-one** [JetBrains/teamcity-messages#131]
```
collected 133 items 
##teamcity[testCount timestamp='2017-04-18T00:36:36.957' count='133']

tests\year2015\test_day1a.py ##teamcity[testStarted timestamp='2017-04-18T00:36:36.958' captureStandardOutput='false' flowId='tests.year2015.test_day1a.TestSolve.test_returns_correct_result' name='tests.year2015.test
_day1a.TestSolve.test_returns_correct_result']
.##teamcity[testFinished timestamp='2017-04-18T00:36:36.959' duration='1' flowId='tests.year2015.test_day1a.TestSolve.test_returns_correct_result' name='tests.year2015.test_day1a.TestSolve.test_returns_correct_result
']
```

You see that ``tests\year2015\test_day1a.py`` in the beginning of the line? Not only it goes to wrong node, but also creates troubles like https://github.com/JetBrains/teamcity-messages/issues/119

I used to solve it on my side by inserting new line before each message finished with https://youtrack.jetbrains.com/issue/PY-22458

Looks like we need to explicitly declare that we *do* support something between new line and message or we do not do that.
We then need to fix your code on Intellij side.

**Comment by throwable-one** [comment]
Intellij now requires runners to report `` ##teamcity[`` at the beginning of new line``

**Comment by shalupov** [comment]
Please attach a case. Anyway I can make some kind of workaround on my side, but it's not like I need to "fix" anything, TeamCity parses service messages out of string easily. I do not understand why it could not be fixed on IntelliJ side

**Comment by throwable-one** [comment]
Here is what I have
```
import unittest



class SampleTest(unittest.TestCase):

    def test_sample(self):
        print(1)
```

I run
```
c:\temp\pytesttest>c:\Python27\Scripts\py.test.exe -p teamcity.pytest_plugin
============================= test session starts =============================
platform win32 -- Python 2.7.12, pytest-3.0.7, py-1.4.32, pluggy-0.4.0
rootdir: c:\temp\pytesttest, inifile:
plugins: django-3.1.2, env-0.6.0
collected 1 items
##teamcity[testCount timestamp='2017-04-18T15:40:25.743' count='1']

test_test.py ##teamcity[testStarted timestamp='2017-04-18T15:40:25.750' captureStandardOutput='false' flowId='test_test.SampleTest.test_sample' name='test_test.SampleTest.test_sample']
.##teamcity[testStdOut timestamp='2017-04-18T15:40:25.756' flowId='test_test.SampleTest.test_sample' name='test_test.SampleTest.test_sample' out='1|n']
##teamcity[testFinished timestamp='2017-04-18T15:40:25.759' duration='1' flowId='test_test.SampleTest.test_sample' name='test_test.SampleTest.test_sample']

```

I agree that it should be fixed on Intellij side as well, but could you please git rid of all that output here? It goes to nowhere because it is not connected to any test and module name before ``testStarted`` leads to trouble

**Comment by shalupov** [comment]
File name and dots are printed by pytest terminal plugin, just run your example without teamcity plugin.
Writing file name could be averted by running pytest in quiet mode (-q).

Probably we don't want to modify default behavior, so fix on IntellIJ side would be good.

**Comment by shalupov** [comment]
Reference code from terminal.py:
```
        self.showfspath = self.verbosity >= 0
        self.showlongtestinfo = self.verbosity > 0
```

**Comment by throwable-one** [comment]
Well, yes. But now file names have no connection to any test. Do you think it is ok?
>  so fix on IntellIJ side would be good.
Since Intellij violates protocol in this case, I am 100% agree I need to fix it.

**Comment by shalupov** [comment]
> But now file names have no connection to any test. Do you think it is ok?
@throwable-one why not?

**Comment by throwable-one** [comment]
Fixed on Intellij side
