### ISSUE TITLE
Provide API to disable buffering.

### ISSUE THREAD

**Issue by throwable-one** [JetBrains/teamcity-messages#132]
For cases like https://youtrack.jetbrains.com/issue/PY-22505 we may benefit from some way to disable buffering like ``TEAMCITY_DISABLE_BUFFERING=1`` env variable.

**Comment by shalupov** [comment]
One can disable buffering via integrated features of test framework (like specifying buffer=False for unittest). Why do you need more?

**Comment by throwable-one** [comment]
You are right, I can use it. Sorry.
