### ISSUE TITLE
Pylint inspection reporter

### ISSUE THREAD

**Issue by rhbvkleef** [JetBrains/teamcity-messages#171]
Would it be possible to add a pylint inspection reporter?

**Comment by shalupov** [comment]
Currently pylint is supported via pytest-pylint: https://pypi.python.org/pypi/pytest-pylint
Probably you're interested in flake8 support too

**Comment by PetrWolf** [comment]
Hi! I'd like to work on this an turn PyLint messages into appropriate [code inspection messages](https://confluence.jetbrains.com/display/TCD18/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-ReportingInspections), enabling direct integration with [TeamCity Code Inspection tab](https://confluence.jetbrains.com/display/TCD18/Working+with+Build+Results#WorkingwithBuildResults-codeInspectionsTab).

That approach has the benefit of fully utilizing the TeamCity Code Inspection tab, including IDE integration, issue categorization, tracking etc. 

PyLint enables such extensions easily through custom [Reporter classes](https://github.com/PyCQA/pylint/tree/master/pylint/reporters).

I have a small prototype and should be able to create a pull request in the next couple of weeks.
Please let me know if this makes sense to you.

**Comment by shalupov** [comment]
@PetrWolf It makes sense, thanks (using pytest-pylint is not that convenient).

Please take a look at the existing code at https://github.com/JetBrains/teamcity-messages/blob/master/teamcity/flake8_v3_plugin.py

For a PR please write at least one integration test to verify your code will work in couple of years too:
https://github.com/JetBrains/teamcity-messages/blob/master/tests/integration-tests/flake8_test.py

**Comment by PetrWolf** [comment]
Apologies for the delay. I should be able to send a pull request within a month.

**Comment by shalupov** [comment]
Released 1.24 with pylint support. Thanks @PetrWolf

**Comment by PetrWolf** [comment]
Great! Thank you!
