### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by Tirzono** [JetBrains/teamcity-messages#246]
Would it be possible to release a new version? It would allow us to use the changes that are done in the last year (as for example #242).

**Comment by Tirzono** [comment]
Hi @mikekidya,

Sorry to ping you, but would it be possible for me to help with releasing a new version? Is there something as a changelog to be written or something else that needs to be done to help you release a new version? I am more than happy to help if time is a problem.

Thanks,
Tirzono

**Comment by jaime-dangelmeier** [comment]
@mikekidya Thanks for the release.
Would it also be possible to publish it to PyPi?

Regards Jaime

**Comment by mikekidya** [comment]
@jaime-dangelmeier sure! 
Currently in progress, but it could take some more time, sorry :(

**Comment by jaime-dangelmeier** [comment]
Thank you very much and have a nice evening, or whatever your local time is.. 😉

**Comment by mikekidya** [comment]
Released 1.29 https://pypi.org/project/teamcity-messages/1.29/ to PyPi 
Enjoy!

**Comment by Tirzono** [comment]
Thank you @mikekidya!

**Comment by jaime-dangelmeier** [comment]
Thank you @mikekidya!

**Comment by georgeth** [comment]
@Tirzono - great work on the fix.
@mikekidya - Thanks for getting this out!
