### ISSUE TITLE
Rename git repo from teamcity-python to teamcity-messages?

### ISSUE THREAD

**Issue by msabramo** [JetBrains/teamcity-messages#59]
This would be less confusing since the package is called `teamcity-messages` on PyPI:

https://pypi.python.org/pypi/teamcity-messages

Cc: @sudarkoff, @djeebus

**Comment by sudarkoff** [comment]
Good idea.

**Comment by djeebus** [comment]
+1!

**Comment by shalupov** [comment]
Done

**Comment by djeebus** [comment]
Nice, thanks!
