### ISSUE TITLE
version number in flake8_plugin.py is out of date

### ISSUE THREAD

**Issue by msabramo** [JetBrains/teamcity-messages#82]
The version number in `flake8_plugin.py` is out of date at `1.9`, which is several versions ago.

https://github.com/JetBrains/teamcity-messages/blob/master/teamcity/flake8_plugin.py#L8

Clearly, it's a burden to have to remember to update the version number in both `setup.py` and here, so it probably makes sense to move to something like `setuptools_scm`. See https://github.com/JetBrains/teamcity-messages/pull/81

**Comment by shalupov** [comment]
Note for myself: try to use setuptools_scm

**Comment by msabramo** [comment]
Any luck with setuptools-scm?

**Comment by shalupov** [comment]
No luck with setuptools-svm, basically I need to reimplement it on Python 2.4.
In the end I decided to use teamcity.__version__ as version source.
Which is still better than having two places to update version

**Comment by shalupov** [comment]
Fixed with 8f6f73fe9acd6db90927d1ab6cc9c3999b71f07d
