### ISSUE TITLE
Doesn't seem to play well with coverage>=4.0

### ISSUE THREAD

**Issue by msabramo** [JetBrains/teamcity-messages#86]
It seems that this uses a function that existed in coverage 3.7.1 called `find_code_units` and that function no longer exists in coverage 4.0. 

I couldn't quite figure out what the equivalent would be in coverage 4.0 but didn't spend much time on it. I wonder if @nedbat might be able to advise.

**Comment by msabramo** [comment]
Hmm just found this:

https://github.com/coagulant/coveralls-python/commit/9821c93b6809fa92f384e76db0a01104b7c7f825
https://github.com/coagulant/coveralls-python/blob/master/coveralls/reporter.py#L24

**Comment by shalupov** [comment]
Thanks for investigation!

**Comment by msabramo** [comment]
Thanks!

**Comment by msabramo** [comment]
Could we get a new release on PyPI when you get a chance?
