### ISSUE TITLE
Test name on build tests page in TeamCity has extraneous space

### ISSUE THREAD

**Issue by westshawn** [JetBrains/teamcity-messages#92]
On the TeamCity build tests page, the test name display has an extra space after the period after the class, and before the test name function name. 
This is visually distracting.

```
TestClass. test_brie(cheese_db)
TestClass. test_cheddar(cheese_db)
```

**Comment by westshawn** [comment]
I think this is not an issue with teamcity-messages since the test name is correct in the build log and overview.

It looks like https://youtrack.jetbrains.com/issue/TW-43633.

**Comment by shalupov** [comment]
Yes, thank you for finding this.
