### ISSUE TITLE
Possibly broken with pytest 2.8.7

### ISSUE THREAD

**Issue by SBoudrias** [JetBrains/teamcity-messages#94]
Hey, sorry to not have a lot of details, but I see the appveyor built haven't run in the last 4 months. Since we've bumped pytest, teamcity-message doesn't seems to work with pytest messages.

Successful tests seems to be counted correctly, but failures are reported in the `Build errors` section outside of the usual teamcity test failure reporting.

From the Teamcity log, I can see that the `FAILED` status is not of the same line as the test name for some result, so this might be related:

```
[14:37:58][Step 4/8] test.test_name
[14:37:59][test.test_name] 
[14:37:59][Step 4/8] 
[14:37:59][Step 4/8] 
[14:37:59][Step 4/8] 
[14:37:59][Step 4/8] FAILED
```

This might also be related to the pytest `flaky` plugin as it'll retry failing tests 4 times in our settings.

**Comment by SBoudrias** [comment]
I figured it'd be easier to reproduce with a code example, so here's one: https://github.com/SBoudrias/__teamcity-flaky-bug

**Comment by shalupov** [comment]
Thank you! I'll take a look

**Comment by shalupov** [comment]
If you set --max-runs to 1 it works as expected, so it's about integration with flaky plugin

**Comment by SBoudrias** [comment]
@shalupov yes, exactly.

**Comment by SBoudrias** [comment]
I also opened an issue on the Flaky side as I wasn't sure which system is incompatible with the other. One of their maintainer gave great insight as to what flaky is doing to trick pytest into not counting extra test passes https://github.com/box/flaky/issues/94#issuecomment-182632460

**Comment by shalupov** [comment]
Thanks, it looks interesting...

**Comment by SBoudrias** [comment]
Fixed on flaky side. Should be all good now.
