### ISSUE TITLE
Using teamcity-messages coverage service messages with django test runner

### ISSUE THREAD

**Issue by wysekm** [JetBrains/teamcity-messages#96]
Hi,

Is it possible to use teamcity-messages to report coverage with the django test runner? I see in the code that it is indeed possible with nose and pytest, however I don't see any code that would allow the same thing for the django test runner.

If I understand the current code correctly the only option to include coverage reports in teamcity is to do that via artefacts. Am I right, or am I missing something?

**Comment by shalupov** [comment]
Sorry for a long reply. Yes, the current way is via artifacts.
It should be possible for django test runner too, it just wasn't implemented yet

**Comment by shalupov** [comment]
According to https://django-testing-docs.readthedocs.io/en/latest/coverage.html coverage run with django should be started via nose and django-nose plugin. Coverage via nosetests works in teamcity-messages
